### ISSUE TITLE
滚动问题

### ISSUE THREAD

**Issue by Rycccccccc** [qq3200341/FLImageShow#1]
滚动问题：放大后，滚到下一张，在滚回来，就不能滚动了，怎么回事呢，大神

**Comment by qq3200341** [comment]
我试了下我的demo里面并没有出现此问题。

**Comment by Rycccccccc** [comment]
我这边出现了，现在不知道什么情况，你的demo，也会，你在iOS 9.0 上面试试，放大一个图片，到最大，再滑动图片到下一张，在滑回来就不能滚动了

**Comment by Rycccccccc** [comment]
你的扣扣多少，我给你发个gif图看下，你分析下是什么原因

**Comment by qq3200341** [comment]
136165767

**Comment by qq3200341** [comment]
修改了这个问题，你更新试下。

**Comment by Rycccccccc** [comment]
恩恩，好的，我试试
